### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by arifinnq** [nicolascerna/emotion-recognition-example#1]
**i try this step..** 

`data_path = '/home/nico/Workspace/Python/Jaffe/data/'
imgs = []
fs = (12, 12)

filenames = sorted(os.listdir(data_path))
d = [] # vector of classification labels

for img_name in filenames:
    img = plt.imread(data_path + img_name)
    imgs.append(img)
    d.append(int(img_name[6]))

imgs = np.asarray(imgs)
d = np.asarray(d)
indices = np.random.randint(0, len(imgs)-1, 5)`

**but i get this error, can you help me**

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-45-82eb7eb3e30f> in <module>()
      7 fs = (12, 12)
      8 
----> 9 filenames = sorted(os.listdir(data_path))
     10 d = [] # vector of classification labels
     11 

OSError: [Errno 2] No such file or directory: '/home/nico/Workspace/Python/Jaffe/data/'
`

can i get your folder data ?? many thanks, for my study...

**Comment by nicolascerna** [comment]
The data can be obtained from here [Jaffe Database](http://www.kasrl.org/jaffe.html). I do not know if I can redistribute that data, so is better if you download it from the original source. The only preprocessing I did was to center and crop the faces so that, in general, the different parts of the face lie in the same areas of the image.
Does this solve your problem?

**Comment by arifinnq** [comment]
really appreciate, it work now.. thanks brother..
i do preprocessing to center and crop the images too, to detect image i use lbpcascade_frontalface_improved.xml too cropping image. 

I want to ask, what is the meaning of this code? do you use 2 calculations of KNN?
 
first :
```
X = np.asarray(lbp_hists)
kf = KF(n_splits=30, shuffle=True).split(X)

train_indices, test_indices =  next(kf)

print('Training images:', train_indices, '\n')
print('Testing images:', test_indices, '\n')

X_train = X[train_indices]
y_train = d[train_indices]

X_test = X[test_indices]
y_test = d[train_indices]

**knn = KNN(n_neighbors=1).fit(X_train, y_train)**
class_prediction = knn.predict(X_test)

print('Predicted Classes:', class_prediction, '\n')
print('Real Classes:', d[test_indices], '\n')
```


second
```
**knn = KNN(n_neighbors=1)**
score_knn = cross_val_score(knn, X, d, cv=10)
print('KNN MEAN PERFORMANCE: ',str(np.mean(score_knn)*100)[:5] + '%')
```

why do you see there are 2 calculations KNN there?? 
if i see from the results of your experiment
```
Predicted Classes: [1 2 5 6 7] 

Real Classes: [1 2 5 6 7]  

```
the prediction from first maybe is 100% right??
and the second calculations is **KNN MEAN PERFORMANCE:  63.66%**
hehe.. sorry many question bro?? :) :)
one more, can explain (X_train, Y_train, X_test, Y_test) I am confused. perhaps there can give me a reference to be able to add in my writing later ??

**Comment by nicolascerna** [comment]
If I understand your question, the answer is the following:
When you are trying to evaluate how well your model performs, you use a testing dataset to observe how well your newly trained model predicts the results using that testing data as input. This testing data is, of course, not used in the training phase. But the problem is the following:
**How do I know if the partition between the training and the testing data is representative?** I mean the model could perform very well for some training-testing partition, but it may be caused just by _chance_.
A way to avoid this problem is to perform several training-testing partitions to train and test your model, and then average the performances obtained from that exercises. This is on many occasions prohibitive because of time restrictions (i.e, the training phase is very time consuming), but whenever you can you should do something like this. In the second use of the **knn** I used the function **crossval** that performs this operation of splitting the data into training and testing a number of times (look at the parameter: cv=10) and then generates a score. This score is far more valuable than the _100%_ calculated in the beginning and you should make your objective to improve this score in the next iterations of the process.

My advice to improve the cross-validation score:
- Use more features and stack them! Features like HoG or GLCM could help.
- Some features could be adding noise or be uninformative for your model: eliminate or replace them!
- Use other classifiers like Neural Networks or Random Forest.
- Tune the parameters of your classifier.
- Have fun! (This sadly doesn't help haha)

Greetings!
